In [1]:
import pandas as pd
import selenium 
import requests
from selenium import webdriver
import warnings
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

warnings.filterwarnings('ignore')

In [2]:
driver=webdriver.Chrome(r"C:\Users\kranthi.kumar\OneDrive - MSC\Desktop\Users May Productivity file\chromedriver.exe")

In [3]:
driver.get('https://www.imdb.com/search/title/?genres=action&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=f11158cc-b50b-4c4d-b0a2-40b32863395b&pf_rd_r=XZ8X52H1R40B7KG5SNZ9&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_1')
driver.maximize_window()

In [4]:
from bs4 import BeautifulSoup

# Get the page source
page_source = driver.page_source

# Create a BeautifulSoup object
soup = BeautifulSoup(page_source, 'html.parser')

# Find all movie name elements
name_elements = soup.find_all('h3', class_='lister-item-header')

# Extract the movie names
movie_names = []
for element in name_elements:
    movie_name = element.a.text.replace('(', '').replace(')', '').replace('\n', '')
    movie_names.append(movie_name)

# Print the movie names
for name in movie_names:
    print(name)

Spider-Man: Across the Spider-Verse
The Dark Knight
The Lord of the Rings: The Return of the King
Inception
The Lord of the Rings: The Fellowship of the Ring
The Lord of the Rings: The Two Towers
The Matrix
Star Wars: Episode V - The Empire Strikes Back
Soorarai Pottru
Star Wars: Episode IV - A New Hope
Terminator 2: Judgment Day
Seven Samurai
Harakiri
Sita Ramam
LÃ©on: The Professional
Gladiator
Spider-Man: Into the Spider-Verse
Indiana Jones and the Raiders of the Lost Ark
Avengers: Endgame
Avengers: Infinity War
Oldboy
The Dark Knight Rises
Aliens
Kaithi
Asuran
Top Gun: Maverick
Heat
North by Northwest
Star Wars: Episode VI - Return of the Jedi
Princess Mononoke
Kantara
Dangal
Raatchasan
K.G.F: Chapter 2
Vikram
Shershaah
Guardians of the Galaxy Vol. 3
Spider-Man: No Way Home
Jurassic Park
Indiana Jones and the Last Crusade
1917
Batman Begins
Kill Bill: Vol. 1
Die Hard
V for Vendetta
Warrior
Demon Slayer the Movie: Mugen Train
Ran
Gangs of Wasseypur
Vikram Vedha

In [5]:
serial=[]
s_n1=soup.find_all('span',class_='lister-item-index unbold text-primary')
for span in s_n1:
    s_no=span.text.strip()
    s_no=s_no.strip('.')
    serial.append(s_no)

In [6]:
duration=[]
du=soup.find_all('span',class_='runtime')
for k in du:
    dur=k.text.replace('min','')
    duration.append(dur)
a=print(','.join(duration))

140 ,152 ,201 ,148 ,178 ,179 ,136 ,124 ,153 ,121 ,137 ,207 ,133 ,163 ,110 ,155 ,117 ,115 ,181 ,149 ,101 ,164 ,137 ,145 ,141 ,130 ,170 ,136 ,131 ,134 ,148 ,161 ,170 ,168 ,175 ,135 ,150 ,148 ,127 ,127 ,119 ,140 ,111 ,132 ,132 ,140 ,117 ,162 ,321 ,147

In [7]:
year=[]
yr=soup.find_all('span',class_='lister-item-year text-muted unbold')
for yrs in yr:
    yr=yrs.text.strip()
    yr=yr.strip('()').replace(',','')
    year.append(yr)

In [8]:
rating=[]
rat=soup.find_all('div',class_='inline-block ratings-imdb-rating')
for mn in rat:
    rt=mn.text.replace('\n','')
    rating.append(rt)

In [9]:
metascore=[]
meta=soup.find_all('div',class_='lister-item-content')
for met in meta:
    movie_title= met.find('h3',class_='lister-item-header').find('a').text
    score_elem=met.find('div',class_='inline-block ratings-metascore')
    
    if score_elem is not None:
        mea=score_elem.text.replace('Metascore','').replace(',','').strip()
        if mea.isnumeric():
            metascore.append({'movie':movie_title,'metascore':mea})
        else:
            metascore.append({'movie':movie_title,'metascore':' '})
            
    else:
        metascore.append({'movie':movie_title,'metascore':' '})
metascore_values = [entry['metascore'] for entry in metascore]
for value in metascore_values:
    print(value)

87
84
94
74
92
87
73
82

90
75
98
85

64
67
87
85
78
68
77
78
84


78
76
98
58
76






64
71
68
65
78
70
69
72
62
71
72
97
89

In [10]:
directors1 = []
directors2 = []
directors3 = []

direct_elems = soup.find_all('div', class_='lister-item-content')

for direct_elem in direct_elems:
    director_names = []
    director_elements = direct_elem.find_all('a')

    for element in director_elements:
        href = element.get('href')
        if href and 'adv_li_dr' in href:
            director_names.append(element.text.strip())

    # Extract the first director
    if director_names:
        director1 = director_names[0]
    else:
        director1 = ' '  # Fill with space if not available
    directors1.append(director1)

    # Extract the second director
    if len(director_names) > 1:
        director2 = director_names[1]
    else:
        director2 = ' '  # Fill with space if not available
    directors2.append(director2)

    # Extract the third director
    if len(director_names) > 2:
        director3 = director_names[2]
    else:
        director3 = ' '  # Fill with space if not available
    directors3.append(director3)

# Print the extracted directors' names
for i in range(len(directors1)):
    print(f"Director1: {directors1[i]}")
    print(f"Director2: {directors2[i]}")
    print(f"Director3: {directors3[i]}")

Director1: Joaquim Dos Santos
Director2: Kemp Powers
Director3: Justin K. Thompson
Director1: Christopher Nolan
Director2:
Director3:
Director1: Peter Jackson
Director2:
Director3:
Director1: Christopher Nolan
Director2:
Director3:
Director1: Peter Jackson
Director2:
Director3:
Director1: Peter Jackson
Director2:
Director3:
Director1: Lana Wachowski
Director2: Lilly Wachowski
Director3:
Director1: Irvin Kershner
Director2:
Director3:
Director1: Sudha Kongara
Director2:
Director3:
Director1: George Lucas
Director2:
Director3:
Director1: James Cameron
Director2:
Director3:
Director1: Akira Kurosawa
Director2:
Director3:
Director1: Masaki Kobayashi
Director2:
Director3:
Director1: Hanu Raghavapudi
Director2:
Director3:
Director1: Luc Besson
Director2:
Director3:
Director1: Ridley Scott
Director2:
Director3:
Director1: Bob Persichetti
Director2: Peter Ramsey
Director3: Rodney Rothman
Director1: Steven Spielberg
Director2:
Director3:
Director1: Anthony Russo
Director2: Joe Russo
Director3:
Director1: Anthony Russo
Director2: Joe Russo
Director3:
Director1: Park Chan-wook
Director2:
Director3:
Director1: Christopher Nolan
Director2:
Director3:
Director1: James Cameron
Director2:
Director3:
Director1: Lokesh Kanagaraj
Director2:
Director3:
Director1: Vetrimaaran
Director2:
Director3:
Director1: Joseph Kosinski
Director2:
Director3:
Director1: Michael Mann
Director2:
Director3:
Director1: Alfred Hitchcock
Director2:
Director3:
Director1: Richard Marquand
Director2:
Director3:
Director1: Hayao Miyazaki
Director2:
Director3:
Director1: Rishab Shetty
Director2:
Director3:
Director1: Nitesh Tiwari
Director2:
Director3:
Director1: Ram Kumar
Director2:
Director3:
Director1: Prashanth Neel
Director2:
Director3:
Director1: Lokesh Kanagaraj
Director2:
Director3:
Director1: Vishnuvardhan
Director2:
Director3:
Director1: James Gunn
Director2:
Director3:
Director1: Jon Watts
Director2:
Director3:
Director1: Steven Spielberg
Director2:
Director3:
Director1: Steven Spielberg
Director2:
Director3:
Director1: Sam Mendes
Director2:
Director3:
Director1: Christopher Nolan
Director2:
Director3:
Director1: Quentin Tarantino
Director2:
Director3:
Director1: John McTiernan
Director2:
Director3:
Director1: James McTeigue
Director2:
Director3:
Director1: Gavin O'Connor
Director2:
Director3:
Director1: Haruo Sotozaki
Director2:
Director3:
Director1: Akira Kurosawa
Director2:
Director3:
Director1: Anurag Kashyap
Director2:
Director3:
Director1: Gayatri
Director2: Pushkar
Director3: Gowtham Selvaraj

In [11]:
directors_data = {
    's_no': serial,
    'movie':movie_names,
    'Director1': directors1,
    'Director2': directors2,
    'Director3': directors3,
    'Duration': duration,
    'year of release': year,
    'Rating': rating,
    'Meatscore': metascore_values
}

df = pd.DataFrame(directors_data)
df.insert(0, 's_no', df.pop('s_no'))  # Move 's_no' column to the first position
df.set_index('s_no', inplace=True)  # Set 's_no' column as the index
df

,movie,Director1,Director2,Director3,Duration,year of release,Rating,Meatscore
s_no,,,,,,,,
1,Spider-Man: Across the Spider-Verse,Joaquim Dos Santos,Kemp Powers,Justin K. Thompson,140,2023,9.1,87
2,The Dark Knight,Christopher Nolan,,,152,2008,9.0,84
3,The Lord of the Rings: The Return of the King,Peter Jackson,,,201,2003,9.0,94
4,Inception,Christopher Nolan,,,148,2010,8.8,74
5,The Lord of the Rings: The Fellowship of the Ring,Peter Jackson,,,178,2001,8.8,92
6,The Lord of the Rings: The Two Towers,Peter Jackson,,,179,2002,8.8,87
7,The Matrix,Lana Wachowski,Lilly Wachowski,,136,1999,8.7,73
8,Star Wars: Episode V - The Empire Strikes Back,Irvin Kershner,,,124,1980,8.7,82
9,Soorarai Pottru,Sudha Kongara,,,153,2020,8.7,
10,Star Wars: Episode IV - A New Hope,George Lucas,,,121,1977,8.6,90
11,Terminator 2: Judgment Day,James Cameron,,,137,1991,8.6,75
12,Seven Samurai,Akira Kurosawa,,,207,1954,8.6,98
13,Harakiri,Masaki Kobayashi,,,133,1962,8.6,85
14,Sita Ramam,Hanu Raghavapudi,,,163,2022,8.6,
15,LÃ©on: The Professional,Luc Besson,,,110,1994,8.5,64
16,Gladiator,Ridley Scott,,,155,2000,8.5,67
17,Spider-Man: Into the Spider-Verse,Bob Persichetti,Peter Ramsey,Rodney Rothman,117,2018,8.4,87
18,Indiana Jones and the Raiders of the Lost Ark,Steven Spielberg,,,115,1981,8.4,85
19,Avengers: Endgame,Anthony Russo,Joe Russo,,181,2019,8.4,78
20,Avengers: Infinity War,Anthony Russo,Joe Russo,,149,2018,8.4,68
21,Oldboy,Park Chan-wook,,,101,2003,8.4,77
22,The Dark Knight Rises,Christopher Nolan,,,164,2012,8.4,78
23,Aliens,James Cameron,,,137,1986,8.4,84
24,Kaithi,Lokesh Kanagaraj,,,145,2019,8.4,
25,Asuran,Vetrimaaran,,,141,2019,8.4,
26,Top Gun: Maverick,Joseph Kosinski,,,130,2022,8.3,78
27,Heat,Michael Mann,,,170,1995,8.3,76
28,North by Northwest,Alfred Hitchcock,,,136,1959,8.3,98
29,Star Wars: Episode VI - Return of the Jedi,Richard Marquand,,,131,1983,8.3,58
30,Princess Mononoke,Hayao Miyazaki,,,134,1997,8.3,76
31,Kantara,Rishab Shetty,,,148,2022,8.3,
32,Dangal,Nitesh Tiwari,,,161,2016,8.3,
33,Raatchasan,Ram Kumar,,,170,2018,8.3,
34,K.G.F: Chapter 2,Prashanth Neel,,,168,2022,8.3,
35,Vikram,Lokesh Kanagaraj,,,175,2022,8.3,
36,Shershaah,Vishnuvardhan,,,135,2021,8.3,
37,Guardians of the Galaxy Vol. 3,James Gunn,,,150,2023,8.2,64
38,Spider-Man: No Way Home,Jon Watts,,,148,2021,8.2,71
39,Jurassic Park,Steven Spielberg,,,127,1993,8.2,68
40,Indiana Jones and the Last Crusade,Steven Spielberg,,,127,1989,8.2,65
41,1917,Sam Mendes,,,119,2019,8.2,78
42,Batman Begins,Christopher Nolan,,,140,2005,8.2,70
43,Kill Bill: Vol. 1,Quentin Tarantino,,,111,2003,8.2,69
44,Die Hard,John McTiernan,,,132,1988,8.2,72
45,V for Vendetta,James McTeigue,,,132,2005,8.2,62
46,Warrior,Gavin O'Connor,,,140,2011,8.2,71
47,Demon Slayer the Movie: Mugen Train,Haruo Sotozaki,,,117,2020,8.2,72
48,Ran,Akira Kurosawa,,,162,1985,8.2,97
49,Gangs of Wasseypur,Anurag Kashyap,,,321,2012,8.2,89
50,Vikram Vedha,Gayatri,Pushkar,Gowtham Selvaraj,147,2017,8.2,

In [12]:
stars1 = []
stars2 = []
stars3 = []
stars4 = []

for direct_elem in direct_elems:
    star_names = []
    star_elements = direct_elem.find_all('a')
    
    for element in star_elements:
        href = element.get('href')
        if href and 'adv_li_st' in href:
            star_names.append(element.text.strip())

    # Extract the first star
    if star_names:
        star1 = star_names[0]
    else:
        star1 = ' '  # Fill with space if not available
    stars1.append(star1)

    # Extract the second star
    if len(star_names) > 1:
        star2 = star_names[1]
    else:
        star2 = ' '  # Fill with space if not available
    stars2.append(star2)

    # Extract the third star
    if len(star_names) > 2:
        star3 = star_names[2]
    else:
        star3 = ' '  # Fill with space if not available
    stars3.append(star3)

    # Extract the fourth star
    if len(star_names) > 3:
        star4 = star_names[3]
    else:
        star4 = ' '  # Fill with space if not available
    stars4.append(star4)

# Create a DataFrame with the star names
stars_data = {
    'Star1': stars1,
    'Star2': stars2,
    'Star3': stars3,
    'Star4': stars4
}

In [13]:
# Get the page source
page_source = driver.page_source

# Create a BeautifulSoup object
soup = BeautifulSoup(page_source, 'html.parser')

# Find all movie name elements
name = soup.find_all('h3', class_='lister-item-header')

# Extract the movie names
movie = []
for i in name:
    na = i.a.text.replace('(', '').replace(')', '').replace('\n', '')
    movie.append(na)

# Print the movie names
for nam in movie:
    print(nam)

Spider-Man: Across the Spider-Verse
The Dark Knight
The Lord of the Rings: The Return of the King
Inception
The Lord of the Rings: The Fellowship of the Ring
The Lord of the Rings: The Two Towers
The Matrix
Star Wars: Episode V - The Empire Strikes Back
Soorarai Pottru
Star Wars: Episode IV - A New Hope
Terminator 2: Judgment Day
Seven Samurai
Harakiri
Sita Ramam
LÃ©on: The Professional
Gladiator
Spider-Man: Into the Spider-Verse
Indiana Jones and the Raiders of the Lost Ark
Avengers: Endgame
Avengers: Infinity War
Oldboy
The Dark Knight Rises
Aliens
Kaithi
Asuran
Top Gun: Maverick
Heat
North by Northwest
Star Wars: Episode VI - Return of the Jedi
Princess Mononoke
Kantara
Dangal
Raatchasan
K.G.F: Chapter 2
Vikram
Shershaah
Guardians of the Galaxy Vol. 3
Spider-Man: No Way Home
Jurassic Park
Indiana Jones and the Last Crusade
1917
Batman Begins
Kill Bill: Vol. 1
Die Hard
V for Vendetta
Warrior
Demon Slayer the Movie: Mugen Train
Ran
Gangs of Wasseypur
Vikram Vedha

In [14]:
votes=[]
vote_elements=soup.select('.sort-num_votes-visible')
for velemt in vote_elements:
    vote_text=velemt.find('span',attrs={'name':'nv'}).text.strip().replace(',','')
    votes.append(vote_text)

In [15]:
generes=[]
genre=soup.find_all('span',class_='genre')
for ge in genre:
    get=ge.text.replace('\n','').strip()
    generes.append(get)

In [16]:
gen1=[]
for element in genre:
    ge1_text=element.text.replace('\n','').strip()
    ge1=ge1_text.split(',')[0]
    gen1.append(ge1)

In [17]:
gen2=[]
for elmt in genre:
    ge2_text=elmt.text.replace('\n','').strip()
    ge2=ge2_text.split(',')[1]
    gen2.append(ge2)

In [18]:
genres=[]
genre_elements=soup.find_all('span',class_='genre')
genre3_list=[]

for elt in genre_elements:
    genre_text=elt.text.replace('\n','').strip()
    genre_list=genre_text.split(',')
    
    genre3=genre_list[2].strip() if len(genre_list) > 2 else ''
    genre3_list.append(genre3)

In [19]:
gross = []

collection = soup.find_all('span', attrs={'name': 'nv', 'data-value': True})
for elem in collection[:50]:  # Limiting the loop to the first 50 elements
    gross_value = elem.text.strip()
    gross_value = gross_value.split('$')[0].replace(',', '')  # Extracting the numerical part and removing commas
    gross.append(gross_value)

In [20]:
movies = soup.find_all('div', class_='lister-item-content')

certification = []
for movie in movies:
    title = movie.find('h3').find('a').text.strip()
    cert_element = movie.find('span', class_='certificate')

    if cert_element is not None:
        cert_text = cert_element.text.strip()
    else:
        cert_text = ''

    certification.append(cert_text)

# Check the length of the certification list
print(len(certification))

50

In [21]:
popularity = []

# Find all popularity elements
pop_elems = soup.find_all('span', class_='lister-item-index unbold text-primary')

# Extract the popularity for each movie
for elem in pop_elems:
    pop = elem.text.strip().replace('.', '')
    popularity.append(pop)

# Create a DataFrame with the movie names and popularity
data = {
    'Movie Name': movie_names,
    'Popularity': popularity
}

In [22]:
gen2

[' Action',
 ' Crime',
 ' Adventure',
 ' Adventure',
 ' Adventure',
 ' Adventure',
 ' Sci-Fi',
 ' Adventure',
 ' Drama',
 ' Adventure',
 ' Sci-Fi',
 ' Drama',
 ' Drama',
 ' Drama',
 ' Crime',
 ' Adventure',
 ' Action',
 ' Adventure',
 ' Adventure',
 ' Adventure',
 ' Drama',
 ' Drama',
 ' Adventure',
 ' Adventure',
 ' Drama',
 ' Drama',
 ' Crime',
 ' Adventure',
 ' Adventure',
 ' Action',
 ' Adventure',
 ' Biography',
 ' Crime',
 ' Crime',
 ' Crime',
 ' Biography',
 ' Adventure',
 ' Adventure',
 ' Adventure',
 ' Adventure',
 ' Drama',
 ' Crime',
 ' Crime',
 ' Thriller',
 ' Drama',
 ' Drama',
 ' Action',
 ' Drama',
 ' Comedy',
 ' Crime']

In [23]:
genre3_list

['Adventure',
 'Drama',
 'Drama',
 'Sci-Fi',
 'Drama',
 'Drama',
 '',
 'Fantasy',
 '',
 'Fantasy',
 '',
 '',
 'Mystery',
 'Mystery',
 'Drama',
 'Drama',
 'Adventure',
 '',
 'Drama',
 'Sci-Fi',
 'Mystery',
 'Thriller',
 'Sci-Fi',
 'Crime',
 '',
 '',
 'Drama',
 'Mystery',
 'Fantasy',
 'Adventure',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Thriller',
 'Drama',
 'Comedy',
 'Fantasy',
 'Sci-Fi',
 '',
 'War',
 'Drama',
 'Drama',
 '',
 'Sci-Fi',
 'Sport',
 'Adventure',
 'War',
 'Crime',
 'Drama']

In [24]:
directors_data = {
    's_no': serial,
    'movie': movie_names,
    'Star_1': stars1,
    'Star_2': stars2,
    'Star_3': stars3,
    'Star_4': stars4,
    'Votes': votes,
    'Genre1': gen1,
    'Genre2': gen2,
    'Genre3': genre3_list,
    'Gross collection': gross,
    'Popularity': popularity,
    'Certification': certification
}

df2 = pd.DataFrame(directors_data)
df2.insert(0, 's_no', df2.pop('s_no'))  # Move 's_no' column to the first position
df2.set_index('s_no', inplace=True)  # Set 's_no' column as the index
df2

,movie,Star_1,Star_2,Star_3,Star_4,Votes,Genre1,Genre2,Genre3,Gross collection,Popularity,Certification
s_no,,,,,,,,,,,,
1,Spider-Man: Across the Spider-Verse,Shameik Moore,Hailee Steinfeld,Brian Tyree Henry,Luna Lauren Velez,64518,Animation,Action,Adventure,64518,1,PG
2,The Dark Knight,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2720822,Action,Crime,Drama,2720822,2,PG-13
3,The Lord of the Rings: The Return of the King,Elijah Wood,Viggo Mortensen,Ian McKellen,Orlando Bloom,1888561,Action,Adventure,Drama,,3,PG-13
4,Inception,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2415126,Action,Adventure,Sci-Fi,1888561,4,PG-13
5,The Lord of the Rings: The Fellowship of the Ring,Elijah Wood,Ian McKellen,Orlando Bloom,Sean Bean,1917162,Action,Adventure,Drama,,5,PG-13
6,The Lord of the Rings: The Two Towers,Elijah Wood,Ian McKellen,Viggo Mortensen,Orlando Bloom,1704549,Action,Adventure,Drama,2415126,6,PG-13
7,The Matrix,Keanu Reeves,Laurence Fishburne,Carrie-Anne Moss,Hugo Weaving,1959456,Action,Sci-Fi,,,7,R
8,Star Wars: Episode V - The Empire Strikes Back,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,1322176,Action,Adventure,Fantasy,1917162,8,PG
9,Soorarai Pottru,Suriya,Paresh Rawal,Urvashi,Aparna Balamurali,119546,Action,Drama,,,9,TV-MA
10,Star Wars: Episode IV - A New Hope,Mark Hamill,Harrison Ford,Carrie Fisher,Alec Guinness,1394619,Action,Adventure,Fantasy,1704549,10,PG
11,Terminator 2: Judgment Day,Arnold Schwarzenegger,Linda Hamilton,Edward Furlong,Robert Patrick,1123902,Action,Sci-Fi,,,11,R
12,Seven Samurai,ToshirÃ´ Mifune,Takashi Shimura,Keiko Tsushima,Yukiko Shimazaki,353037,Action,Drama,,1959456,12,Not Rated
13,Harakiri,Tatsuya Nakadai,Akira Ishihama,Shima Iwashita,TetsurÃ´ Tanba,61089,Action,Drama,Mystery,,13,Not Rated
14,Sita Ramam,Dulquer Salmaan,Mrunal Thakur,Rashmika Mandanna,Sumanth,60082,Action,Drama,Mystery,1322176,14,U
15,LÃ©on: The Professional,Jean Reno,Gary Oldman,Natalie Portman,Danny Aiello,1190333,Action,Crime,Drama,,15,R
16,Gladiator,Russell Crowe,Joaquin Phoenix,Connie Nielsen,Oliver Reed,1537293,Action,Adventure,Drama,119546,16,R
17,Spider-Man: Into the Spider-Verse,Shameik Moore,Jake Johnson,Hailee Steinfeld,Mahershala Ali,574033,Animation,Action,Adventure,1394619,17,PG
18,Indiana Jones and the Raiders of the Lost Ark,Harrison Ford,Karen Allen,Paul Freeman,John Rhys-Davies,987585,Action,Adventure,,,18,PG
19,Avengers: Endgame,Robert Downey Jr.,Chris Evans,Mark Ruffalo,Chris Hemsworth,1181806,Action,Adventure,Drama,1123902,19,PG-13
20,Avengers: Infinity War,Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,Chris Evans,1125077,Action,Adventure,Sci-Fi,,20,PG-13
21,Oldboy,Choi Min-sik,Yoo Ji-tae,Kang Hye-jeong,Kim Byeong-Ok,596920,Action,Drama,Mystery,353037,21,R
22,The Dark Knight Rises,Christian Bale,Tom Hardy,Anne Hathaway,Gary Oldman,1742957,Action,Drama,Thriller,,22,PG-13
23,Aliens,Sigourney Weaver,Michael Biehn,Carrie Henn,Paul Reiser,732985,Action,Adventure,Sci-Fi,61089,23,R
24,Kaithi,Karthi,Narain,Arjun Das,George Maryan,36167,Action,Adventure,Crime,60082,24,Not Rated
25,Asuran,Dhanush,Manju Warrier,Prakash Raj,Pasupathy,31220,Action,Drama,,1190333,25,Not Rated
26,Top Gun: Maverick,Tom Cruise,Jennifer Connelly,Miles Teller,Val Kilmer,592075,Action,Drama,,,26,PG-13
27,Heat,Al Pacino,Robert De Niro,Val Kilmer,Jon Voight,677203,Action,Crime,Drama,1537293,27,R
28,North by Northwest,Cary Grant,Eva Marie Saint,James Mason,Jessie Royce Landis,334798,Action,Adventure,Mystery,,28,Approved
29,Star Wars: Episode VI - Return of the Jedi,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,1078425,Action,Adventure,Fantasy,574033,29,PG
30,Princess Mononoke,YÃ´ji Matsuda,Yuriko Ishida,YÃ»ko Tanaka,Billy Crudup,407142,Animation,Action,Adventure,,30,PG-13
31,Kantara,Rishab Shetty,Kishore Kumar G.,Achyuth Kumar,Sapthami Gowda,95596,Action,Adventure,Drama,987585,31,Not Rated
32,Dangal,Aamir Khan,Sakshi Tanwar,Fatima Sana Shaikh,Sanya Malhotra,197502,Action,Biography,Drama,,32,Not Rated
33,Raatchasan,Vishnu Vishal,Amala Paul,Radha Ravi,Sangili Murugan,46988,Action,Crime,Drama,1181806,33,Not Rated
34,K.G.F: Chapter 2,Yash,Sanjay Dutt,Raveena Tandon,Srinidhi Shetty,139730,Action,Crime,Drama,,34,Not Rated
35,Vikram,Kamal Haasan,Vijay Sethupathi,Fahadh Faasil,Narain,63919,Action,Crime,Thriller,1125077,35,UA
36,Shershaah,Sidharth Malhotra,Kiara Advani,Shiv Panditt,Pranay Pachauri,124859,Action,Biography,Drama,,36,TV-14
37,Guardians of the Galaxy Vol. 3,Chris Pratt,Chukwudi Iwuji,Bradley Cooper,Pom Klementieff,159228,Action,Adventure,Comedy,596920,37,PG-13
38,Spider-Man: No Way Home,Tom Holland,Zendaya,Benedict Cumberbatch,Jacob Batalon,798974,Action,Adventure,Fantasy,,38,PG-13
39,Jurassic Park,Sam Neill,Laura Dern,Jeff Goldblum,Richard Attenborough,1014710,Action,Adventure,Sci-Fi,1742957,39,PG-13
40,Indiana Jones and the Last Crusade,Harrison Ford,Sean Connery,Alison Doody,Denholm Elliott,771881,Action,Adventure,,,40,PG-13
41,1917,Dean-Charles Chapman,George MacKay,Daniel Mays,Colin Firth,621897,Action,Drama,War,732985,41,R
42,Batman Begins,Christian Bale,Michael Caine,Ken Watanabe,Liam Neeson,1504338,Action,Crime,Drama,,42,PG-13
43,Kill Bill: Vol. 1,Uma Thurman,David Carradine,Daryl Hannah,Michael Madsen,1141529,Action,Crime,Drama,36167,43,R
44,Die Hard,Bruce Willis,Alan Rickman,Bonnie Bedelia,Reginald VelJohnson,901815,Action,Thriller,,31220,44,R
45,V for Vendetta,Hugo Weaving,Natalie Portman,Rupert Graves,Stephen Rea,1141386,Action,Drama,Sci-Fi,592075,45,R
46,Warrior,Tom Hardy,Nick Nolte,Joel Edgerton,Jennifer Morrison,482056,Action,Drama,Sport,,46,PG-13
47,Demon Slayer the Movie: Mugen Train,Natsuki Hanae,Akari KitÃ´,Yoshitsugu Matsuoka,Hiro Shimono,64546,Animation,Action,Adventure,677203,47,R
48,Ran,Tatsuya Nakadai,Akira Terao,Jinpachi Nezu,Daisuke RyÃ»,129268,Action,Drama,War,,48,R
49,Gangs of Wasseypur,Manoj Bajpayee,Nawazuddin Siddiqui,Tigmanshu Dhulia,Richa Chadha,99411,Action,Comedy,Crime,334798,49,Not Rated
50,Vikram Vedha,Madhavan,Vijay Sethupathi,Shraddha Srinath,Kathir,47726,Action,Crime,Drama,,50,Not Rated

In [25]:
# Save df to a CSV file
df.to_csv('directors_data.csv', index=False)

# Save df2 to a CSV file
df2.to_csv('movies_data.csv', index=False)

In [26]:
import sqlite3
import pandas as pd

In [27]:
conn = sqlite3.connect('mydatabase.db')

In [28]:
df1 = pd.read_csv('directors_data.csv')
df2 = pd.read_csv('movies_data.csv')

In [29]:
df1.to_sql('table1', conn, if_exists='replace', index=False)
df2.to_sql('table2', conn, if_exists='replace', index=False)

50

In [30]:
conn.commit()

# Table 1: Sno, MovieName, Director Name, Duration, genre, ratings

# 1)  Display all the details of movies created by directors Christopher and Matt Reeves.

In [44]:
# Print the movies directed by Christopher Nolan
christopher_movies = filtered_movies[(filtered_movies['Director1'] == 'Christopher Nolan') |
                                    (filtered_movies['Director2'] == 'Christopher Nolan') |
                                    (filtered_movies['Director3'] == 'Christopher Nolan')]

if not christopher_movies.empty:
    print("Movies directed by Christopher Nolan:")
    print(christopher_movies['movie'])
else:
    print("No movies directed by Christopher Nolan found in the filtered movies.")

# Check if any movie directed by Matt Reeves is present in the top 50
top_50_director_matt_reeves = any(filtered_movies['Director1'] == 'Matt Reeves') or \
                              any(filtered_movies['Director2'] == 'Matt Reeves') or \
                              any(filtered_movies['Director3'] == 'Matt Reeves')

# Display the result
if not top_50_director_matt_reeves:
    print("No movies of Matt Reeves found in the top 50.")

Movies directed by Christopher Nolan:
1           The Dark Knight
3                 Inception
21    The Dark Knight Rises
41            Batman Begins
Name: movie, dtype: object
No movies of Matt Reeves found in the top 50.

In [45]:
create_table_query = '''
CREATE TABLE new_directors (
    s_no INTEGER PRIMARY KEY,
    movie TEXT,
    Director1 TEXT,
    Director2 TEXT,
    Director3 TEXT,
    Duration INTEGER,
    year_of_release INTEGER,
    Rating REAL,
    Meatscore INTEGER
)
'''

# 2) Display all the details of movies with a duration of 140 minutes to 190 minutes.

In [46]:
df['Duration'] = pd.to_numeric(df['Duration'], errors='coerce')  # Convert 'Duration' column to numeric type

filtered_movies = df[(df['Duration'] >= 140) & (df['Duration'] <= 190)]
print(filtered_movies)

                                                movie           Director1  \
0                 Spider-Man: Across the Spider-Verse  Joaquim Dos Santos
1                                     The Dark Knight   Christopher Nolan
3                                           Inception   Christopher Nolan
4   The Lord of the Rings: The Fellowship of the Ring       Peter Jackson
5               The Lord of the Rings: The Two Towers       Peter Jackson
8                                     Soorarai Pottru       Sudha Kongara
13                                         Sita Ramam    Hanu Raghavapudi
15                                          Gladiator        Ridley Scott
18                                  Avengers: Endgame       Anthony Russo
19                             Avengers: Infinity War       Anthony Russo
21                              The Dark Knight Rises   Christopher Nolan
23                                             Kaithi    Lokesh Kanagaraj
24                                             Asuran         Vetrimaaran
26                                               Heat        Michael Mann
30                                            Kantara       Rishab Shetty
31                                             Dangal       Nitesh Tiwari
32                                         Raatchasan           Ram Kumar
33                                   K.G.F: Chapter 2      Prashanth Neel
34                                             Vikram    Lokesh Kanagaraj
36                     Guardians of the Galaxy Vol. 3          James Gunn
37                            Spider-Man: No Way Home           Jon Watts
41                                      Batman Begins   Christopher Nolan
45                                            Warrior      Gavin O'Connor
47                                                Ran      Akira Kurosawa
49                                       Vikram Vedha             Gayatri

      Director2           Director3  Duration  year of release  Rating  \
0   Kemp Powers  Justin K. Thompson       140             2023     9.1
1                                         152             2008     9.0
3                                         148             2010     8.8
4                                         178             2001     8.8
5                                         179             2002     8.8
8                                         153             2020     8.7
13                                        163             2022     8.6
15                                        155             2000     8.5
18    Joe Russo                           181             2019     8.4
19    Joe Russo                           149             2018     8.4
21                                        164             2012     8.4
23                                        145             2019     8.4
24                                        141             2019     8.4
26                                        170             1995     8.3
30                                        148             2022     8.3
31                                        161             2016     8.3
32                                        170             2018     8.3
33                                        168             2022     8.3
34                                        175             2022     8.3
36                                        150             2023     8.2
37                                        148             2021     8.2
41                                        140             2005     8.2
45                                        140             2011     8.2
47                                        162             1985     8.2
49      Pushkar    Gowtham Selvaraj       147             2017     8.2

   Meatscore
0         87
1         84
3         74
4         92
5         87
8
13
15        67
18        78
19        68
21        78
23
24
26        76
30
31
32
33
34
36        64
37        71
41        70
45        71
47        97
49

# 3) Display all details of movies with ratings above 7 in ascending order.

In [47]:
import sqlite3
import pandas as pd

# Create a connection to the SQLite database
conn = sqlite3.connect('mydatabase.db')

# Read the CSV file into a DataFrame
df = pd.read_csv('directors_data.csv')

# Insert the data into the directors table
df.to_sql('directors', conn, if_exists='replace', index=False)

# Define the SQL query
query = "SELECT * FROM directors WHERE Rating > 7 ORDER BY Rating ASC"

# Execute the SQL query and fetch the results
result = pd.read_sql_query(query, conn)

# Close the database connection
conn.close()

# Display the result
print(result)

                                                movie           Director1  \
0                      Guardians of the Galaxy Vol. 3          James Gunn
1                             Spider-Man: No Way Home           Jon Watts
2                                       Jurassic Park    Steven Spielberg
3                  Indiana Jones and the Last Crusade    Steven Spielberg
4                                                1917          Sam Mendes
5                                       Batman Begins   Christopher Nolan
6                                   Kill Bill: Vol. 1   Quentin Tarantino
7                                            Die Hard      John McTiernan
8                                      V for Vendetta      James McTeigue
9                                             Warrior      Gavin O'Connor
10                Demon Slayer the Movie: Mugen Train      Haruo Sotozaki
11                                                Ran      Akira Kurosawa
12                                 Gangs of Wasseypur      Anurag Kashyap
13                                       Vikram Vedha             Gayatri
14                                  Top Gun: Maverick     Joseph Kosinski
15                                               Heat        Michael Mann
16                                 North by Northwest    Alfred Hitchcock
17         Star Wars: Episode VI - Return of the Jedi    Richard Marquand
18                                  Princess Mononoke      Hayao Miyazaki
19                                            Kantara       Rishab Shetty
20                                             Dangal       Nitesh Tiwari
21                                         Raatchasan           Ram Kumar
22                                   K.G.F: Chapter 2      Prashanth Neel
23                                             Vikram    Lokesh Kanagaraj
24                                          Shershaah       Vishnuvardhan
25                  Spider-Man: Into the Spider-Verse     Bob Persichetti
26      Indiana Jones and the Raiders of the Lost Ark    Steven Spielberg
27                                  Avengers: Endgame       Anthony Russo
28                             Avengers: Infinity War       Anthony Russo
29                                             Oldboy      Park Chan-wook
30                              The Dark Knight Rises   Christopher Nolan
31                                             Aliens       James Cameron
32                                             Kaithi    Lokesh Kanagaraj
33                                             Asuran         Vetrimaaran
34                             LÃ©on: The Professional          Luc Besson
35                                          Gladiator        Ridley Scott
36                 Star Wars: Episode IV - A New Hope        George Lucas
37                         Terminator 2: Judgment Day       James Cameron
38                                      Seven Samurai      Akira Kurosawa
39                                           Harakiri    Masaki Kobayashi
40                                         Sita Ramam    Hanu Raghavapudi
41                                         The Matrix      Lana Wachowski
42     Star Wars: Episode V - The Empire Strikes Back      Irvin Kershner
43                                    Soorarai Pottru       Sudha Kongara
44                                          Inception   Christopher Nolan
45  The Lord of the Rings: The Fellowship of the Ring       Peter Jackson
46              The Lord of the Rings: The Two Towers       Peter Jackson
47                                    The Dark Knight   Christopher Nolan
48      The Lord of the Rings: The Return of the King       Peter Jackson
49                Spider-Man: Across the Spider-Verse  Joaquim Dos Santos

          Director2           Director3  Duration  year of release  Rating  \
0                                             150             2023     8.2
1                                             148             2021     8.2
2                                             127             1993     8.2
3                                             127             1989     8.2
4                                             119             2019     8.2
5                                             140             2005     8.2
6                                             111             2003     8.2
7                                             132             1988     8.2
8                                             132             2005     8.2
9                                             140             2011     8.2
10                                            117             2020     8.2
11                                            162             1985     8.2
12                                            321             2012     8.2
13          Pushkar    Gowtham Selvaraj       147             2017     8.2
14                                            130             2022     8.3
15                                            170             1995     8.3
16                                            136             1959     8.3
17                                            131             1983     8.3
18                                            134             1997     8.3
19                                            148             2022     8.3
20                                            161             2016     8.3
21                                            170             2018     8.3
22                                            168             2022     8.3
23                                            175             2022     8.3
24                                            135             2021     8.3
25     Peter Ramsey      Rodney Rothman       117             2018     8.4
26                                            115             1981     8.4
27        Joe Russo                           181             2019     8.4
28        Joe Russo                           149             2018     8.4
29                                            101             2003     8.4
30                                            164             2012     8.4
31                                            137             1986     8.4
32                                            145             2019     8.4
33                                            141             2019     8.4
34                                            110             1994     8.5
35                                            155             2000     8.5
36                                            121             1977     8.6
37                                            137             1991     8.6
38                                            207             1954     8.6
39                                            133             1962     8.6
40                                            163             2022     8.6
41  Lilly Wachowski                           136             1999     8.7
42                                            124             1980     8.7
43                                            153             2020     8.7
44                                            148             2010     8.8
45                                            178             2001     8.8
46                                            179             2002     8.8
47                                            152             2008     9.0
48                                            201             2003     9.0
49      Kemp Powers  Justin K. Thompson       140             2023     9.1

   Meatscore
0         64
1         71
2         68
3         65
4         78
5         70
6         69
7         72
8         62
9         71
10        72
11        97
12        89
13
14        78
15        76
16        98
17        58
18        76
19
20
21
22
23
24
25        87
26        85
27        78
28        68
29        77
30        78
31        84
32
33
34        64
35        67
36        90
37        75
38        98
39        85
40
41        73
42        82
43
44        74
45        92
46        87
47        84
48        94
49        87

# 4) Display all movie names in descending order.

In [49]:

# Sort the DataFrame by movie names in descending order
sorted_movies = df.sort_values('movie', ascending=False)

# Display the movie names in descending order
print(sorted_movies['movie'])

45                                              Warrior
49                                         Vikram Vedha
34                                               Vikram
44                                       V for Vendetta
25                                    Top Gun: Maverick
6                                            The Matrix
5                 The Lord of the Rings: The Two Towers
2         The Lord of the Rings: The Return of the King
4     The Lord of the Rings: The Fellowship of the Ring
21                                The Dark Knight Rises
1                                       The Dark Knight
10                           Terminator 2: Judgment Day
28           Star Wars: Episode VI - Return of the Jedi
7        Star Wars: Episode V - The Empire Strikes Back
9                    Star Wars: Episode IV - A New Hope
37                              Spider-Man: No Way Home
16                    Spider-Man: Into the Spider-Verse
0                   Spider-Man: Across the Spider-Verse
8                                       Soorarai Pottru
13                                           Sita Ramam
35                                            Shershaah
11                                        Seven Samurai
47                                                  Ran
32                                           Raatchasan
29                                    Princess Mononoke
20                                               Oldboy
27                                   North by Northwest
14                               LÃ©on: The Professional
42                                    Kill Bill: Vol. 1
30                                              Kantara
23                                               Kaithi
33                                     K.G.F: Chapter 2
38                                        Jurassic Park
17        Indiana Jones and the Raiders of the Lost Ark
39                   Indiana Jones and the Last Crusade
3                                             Inception
26                                                 Heat
12                                             Harakiri
36                       Guardians of the Galaxy Vol. 3
15                                            Gladiator
48                                   Gangs of Wasseypur
43                                             Die Hard
46                  Demon Slayer the Movie: Mugen Train
31                                               Dangal
41                                        Batman Begins
19                               Avengers: Infinity War
18                                    Avengers: Endgame
24                                               Asuran
22                                               Aliens
40                                                 1917
Name: movie, dtype: object

# 5) Display movie name starts with âPâ and their rating is greater than 7.

In [50]:

# Filter movies by movie names starting with 'P' and rating greater than 7
filtered_movies = df[(df['movie'].str.startswith('P')) & (df['Rating'] > 7)]

# Display the movie names and ratings
print(filtered_movies[['movie', 'Rating']])

                movie  Rating
29  Princess Mononoke     8.3

# Table 2: Movie Name, stars, votes, Genre, Gross collection, popularity, Certification

# 1) Display all movie names with star Arnold Schwarzenegger in ascending order.

In [52]:
# Create a list of column names containing stars
star_columns = ['Star_1', 'Star_2', 'Star_3', 'Star_4']

# Filter movies by star Arnold Schwarzenegger
filtered_movies = df2[df2[star_columns].apply(lambda x: 'Arnold Schwarzenegger' in x.values, axis=1)]

# Sort the movie names in ascending order
sorted_movies = filtered_movies.sort_values('movie')

# Display the movie names
print(sorted_movies['movie'])

10    Terminator 2: Judgment Day
Name: movie, dtype: object

# 2) Display all details of the movie with the highest number of votes.

In [58]:
# Find the movie with the highest number of votes
highest_votes_movie = df2[df2['Votes'] == df2['Votes'].max()]

# Display all details of the movie
print(highest_votes_movie)

             movie          Star_1        Star_2         Star_3  \
1  The Dark Knight  Christian Bale  Heath Ledger  Aaron Eckhart

          Star_4    Votes  Genre1  Genre2 Genre3  Gross collection  \
1  Michael Caine  2720822  Action   Crime  Drama         2720822.0

   Popularity Certification
1           2         PG-13

# 3) Display movie names with gross collections in descending order.

In [60]:
# Sort the DataFrame by gross collection in descending order
sorted_movies = df2.sort_values('Gross collection', ascending=False)

# Display the movie names with gross collections in descending order
movie_names = sorted_movies[['movie', 'Gross collection']]
print(movie_names)

                                                movie  Gross collection
1                                     The Dark Knight         2720822.0
5               The Lord of the Rings: The Two Towers         2415126.0
11                                      Seven Samurai         1959456.0
7      Star Wars: Episode V - The Empire Strikes Back         1917162.0
3                                           Inception         1888561.0
38                                      Jurassic Park         1742957.0
9                  Star Wars: Episode IV - A New Hope         1704549.0
26                                               Heat         1537293.0
16                  Spider-Man: Into the Spider-Verse         1394619.0
13                                         Sita Ramam         1322176.0
24                                             Asuran         1190333.0
32                                         Raatchasan         1181806.0
34                                             Vikram         1125077.0
18                                  Avengers: Endgame         1123902.0
30                                            Kantara          987585.0
40                                               1917          732985.0
46                Demon Slayer the Movie: Mugen Train          677203.0
36                     Guardians of the Galaxy Vol. 3          596920.0
44                                     V for Vendetta          592075.0
28         Star Wars: Episode VI - Return of the Jedi          574033.0
20                                             Oldboy          353037.0
48                                 Gangs of Wasseypur          334798.0
15                                          Gladiator          119546.0
0                 Spider-Man: Across the Spider-Verse           64518.0
22                                             Aliens           61089.0
23                                             Kaithi           60082.0
42                                  Kill Bill: Vol. 1           36167.0
43                                           Die Hard           31220.0
2       The Lord of the Rings: The Return of the King               NaN
4   The Lord of the Rings: The Fellowship of the Ring               NaN
6                                          The Matrix               NaN
8                                     Soorarai Pottru               NaN
10                         Terminator 2: Judgment Day               NaN
12                                           Harakiri               NaN
14                             LÃ©on: The Professional               NaN
17      Indiana Jones and the Raiders of the Lost Ark               NaN
19                             Avengers: Infinity War               NaN
21                              The Dark Knight Rises               NaN
25                                  Top Gun: Maverick               NaN
27                                 North by Northwest               NaN
29                                  Princess Mononoke               NaN
31                                             Dangal               NaN
33                                   K.G.F: Chapter 2               NaN
35                                          Shershaah               NaN
37                            Spider-Man: No Way Home               NaN
39                 Indiana Jones and the Last Crusade               NaN
41                                      Batman Begins               NaN
45                                            Warrior               NaN
47                                                Ran               NaN
49                                       Vikram Vedha               NaN

# 4) Display the gross collection of movies with the star Arnold.

In [61]:
# Filter movies by star Arnold Schwarzenegger
filtered_movies = df2[df2['Star_1'].str.contains('Arnold', case=False) |
                      df2['Star_2'].str.contains('Arnold', case=False) |
                      df2['Star_3'].str.contains('Arnold', case=False) |
                      df2['Star_4'].str.contains('Arnold', case=False)]

# Display the movie names and their gross collections
movie_gross = filtered_movies[['movie', 'Gross collection']]
print(movie_gross)

                         movie  Gross collection
10  Terminator 2: Judgment Day               NaN

# 5) Display all details of movies with comedy and action genres

In [62]:
# Filter movies by comedy and action genres
filtered_movies = df2[(df2['Genre1'] == 'Comedy') | (df2['Genre2'] == 'Comedy') | (df2['Genre3'] == 'Comedy') &
                      (df2['Genre1'] == 'Action') | (df2['Genre2'] == 'Action') | (df2['Genre3'] == 'Action')]

# Display all details of the filtered movies
print(filtered_movies)

                             movie       Star_1          Star_2  \
36  Guardians of the Galaxy Vol. 3  Chris Pratt  Chukwudi Iwuji

            Star_3           Star_4   Votes  Genre1      Genre2  Genre3  \
36  Bradley Cooper  Pom Klementieff  159228  Action   Adventure  Comedy

    Gross collection  Popularity Certification
36          596920.0          37         PG-13

# Making subquery :

# 1) Display all details from both tables where movie names are the same.

In [66]:
merged_data = pd.merge(df, df2, on='movie')
print(merged_data)

                                                movie           Director1  \
0                 Spider-Man: Across the Spider-Verse  Joaquim Dos Santos
1                                     The Dark Knight   Christopher Nolan
2       The Lord of the Rings: The Return of the King       Peter Jackson
3                                           Inception   Christopher Nolan
4   The Lord of the Rings: The Fellowship of the Ring       Peter Jackson
5               The Lord of the Rings: The Two Towers       Peter Jackson
6                                          The Matrix      Lana Wachowski
7      Star Wars: Episode V - The Empire Strikes Back      Irvin Kershner
8                                     Soorarai Pottru       Sudha Kongara
9                  Star Wars: Episode IV - A New Hope        George Lucas
10                         Terminator 2: Judgment Day       James Cameron
11                                      Seven Samurai      Akira Kurosawa
12                                           Harakiri    Masaki Kobayashi
13                                         Sita Ramam    Hanu Raghavapudi
14                             LÃ©on: The Professional          Luc Besson
15                                          Gladiator        Ridley Scott
16                  Spider-Man: Into the Spider-Verse     Bob Persichetti
17      Indiana Jones and the Raiders of the Lost Ark    Steven Spielberg
18                                  Avengers: Endgame       Anthony Russo
19                             Avengers: Infinity War       Anthony Russo
20                                             Oldboy      Park Chan-wook
21                              The Dark Knight Rises   Christopher Nolan
22                                             Aliens       James Cameron
23                                             Kaithi    Lokesh Kanagaraj
24                                             Asuran         Vetrimaaran
25                                  Top Gun: Maverick     Joseph Kosinski
26                                               Heat        Michael Mann
27                                 North by Northwest    Alfred Hitchcock
28         Star Wars: Episode VI - Return of the Jedi    Richard Marquand
29                                  Princess Mononoke      Hayao Miyazaki
30                                            Kantara       Rishab Shetty
31                                             Dangal       Nitesh Tiwari
32                                         Raatchasan           Ram Kumar
33                                   K.G.F: Chapter 2      Prashanth Neel
34                                             Vikram    Lokesh Kanagaraj
35                                          Shershaah       Vishnuvardhan
36                     Guardians of the Galaxy Vol. 3          James Gunn
37                            Spider-Man: No Way Home           Jon Watts
38                                      Jurassic Park    Steven Spielberg
39                 Indiana Jones and the Last Crusade    Steven Spielberg
40                                               1917          Sam Mendes
41                                      Batman Begins   Christopher Nolan
42                                  Kill Bill: Vol. 1   Quentin Tarantino
43                                           Die Hard      John McTiernan
44                                     V for Vendetta      James McTeigue
45                                            Warrior      Gavin O'Connor
46                Demon Slayer the Movie: Mugen Train      Haruo Sotozaki
47                                                Ran      Akira Kurosawa
48                                 Gangs of Wasseypur      Anurag Kashyap
49                                       Vikram Vedha             Gayatri

          Director2           Director3  Duration  year of release  Rating  \
0       Kemp Powers  Justin K. Thompson       140             2023     9.1
1                                             152             2008     9.0
2                                             201             2003     9.0
3                                             148             2010     8.8
4                                             178             2001     8.8
5                                             179             2002     8.8
6   Lilly Wachowski                           136             1999     8.7
7                                             124             1980     8.7
8                                             153             2020     8.7
9                                             121             1977     8.6
10                                            137             1991     8.6
11                                            207             1954     8.6
12                                            133             1962     8.6
13                                            163             2022     8.6
14                                            110             1994     8.5
15                                            155             2000     8.5
16     Peter Ramsey      Rodney Rothman       117             2018     8.4
17                                            115             1981     8.4
18        Joe Russo                           181             2019     8.4
19        Joe Russo                           149             2018     8.4
20                                            101             2003     8.4
21                                            164             2012     8.4
22                                            137             1986     8.4
23                                            145             2019     8.4
24                                            141             2019     8.4
25                                            130             2022     8.3
26                                            170             1995     8.3
27                                            136             1959     8.3
28                                            131             1983     8.3
29                                            134             1997     8.3
30                                            148             2022     8.3
31                                            161             2016     8.3
32                                            170             2018     8.3
33                                            168             2022     8.3
34                                            175             2022     8.3
35                                            135             2021     8.3
36                                            150             2023     8.2
37                                            148             2021     8.2
38                                            127             1993     8.2
39                                            127             1989     8.2
40                                            119             2019     8.2
41                                            140             2005     8.2
42                                            111             2003     8.2
43                                            132             1988     8.2
44                                            132             2005     8.2
45                                            140             2011     8.2
46                                            117             2020     8.2
47                                            162             1985     8.2
48                                            321             2012     8.2
49          Pushkar    Gowtham Selvaraj       147             2017     8.2

   Meatscore                 Star_1                Star_2  \
0         87          Shameik Moore      Hailee Steinfeld
1         84         Christian Bale          Heath Ledger
2         94            Elijah Wood       Viggo Mortensen
3         74      Leonardo DiCaprio  Joseph Gordon-Levitt
4         92            Elijah Wood          Ian McKellen
5         87            Elijah Wood          Ian McKellen
6         73           Keanu Reeves    Laurence Fishburne
7         82            Mark Hamill         Harrison Ford
8                            Suriya          Paresh Rawal
9         90            Mark Hamill         Harrison Ford
10        75  Arnold Schwarzenegger        Linda Hamilton
11        98         ToshirÃ´ Mifune       Takashi Shimura
12        85        Tatsuya Nakadai        Akira Ishihama
13                  Dulquer Salmaan         Mrunal Thakur
14        64              Jean Reno           Gary Oldman
15        67          Russell Crowe       Joaquin Phoenix
16        87          Shameik Moore          Jake Johnson
17        85          Harrison Ford           Karen Allen
18        78      Robert Downey Jr.           Chris Evans
19        68      Robert Downey Jr.       Chris Hemsworth
20        77           Choi Min-sik            Yoo Ji-tae
21        78         Christian Bale             Tom Hardy
22        84       Sigourney Weaver         Michael Biehn
23                           Karthi                Narain
24                          Dhanush         Manju Warrier
25        78             Tom Cruise     Jennifer Connelly
26        76              Al Pacino        Robert De Niro
27        98             Cary Grant       Eva Marie Saint
28        58            Mark Hamill         Harrison Ford
29        76           YÃ´ji Matsuda         Yuriko Ishida
30                    Rishab Shetty      Kishore Kumar G.
31                       Aamir Khan         Sakshi Tanwar
32                    Vishnu Vishal            Amala Paul
33                             Yash           Sanjay Dutt
34                     Kamal Haasan      Vijay Sethupathi
35                Sidharth Malhotra          Kiara Advani
36        64            Chris Pratt        Chukwudi Iwuji
37        71            Tom Holland               Zendaya
38        68              Sam Neill            Laura Dern
39        65          Harrison Ford          Sean Connery
40        78   Dean-Charles Chapman         George MacKay
41        70         Christian Bale         Michael Caine
42        69            Uma Thurman       David Carradine
43        72           Bruce Willis          Alan Rickman
44        62           Hugo Weaving       Natalie Portman
45        71              Tom Hardy            Nick Nolte
46        72          Natsuki Hanae            Akari KitÃ´
47        97        Tatsuya Nakadai           Akira Terao
48        89         Manoj Bajpayee   Nawazuddin Siddiqui
49                         Madhavan      Vijay Sethupathi

                  Star_3                Star_4    Votes     Genre1  \
0      Brian Tyree Henry     Luna Lauren Velez    64518  Animation
1          Aaron Eckhart         Michael Caine  2720822     Action
2           Ian McKellen         Orlando Bloom  1888561     Action
3            Elliot Page          Ken Watanabe  2415126     Action
4          Orlando Bloom             Sean Bean  1917162     Action
5        Viggo Mortensen         Orlando Bloom  1704549     Action
6       Carrie-Anne Moss          Hugo Weaving  1959456     Action
7          Carrie Fisher    Billy Dee Williams  1322176     Action
8                Urvashi     Aparna Balamurali   119546     Action
9          Carrie Fisher         Alec Guinness  1394619     Action
10        Edward Furlong        Robert Patrick  1123902     Action
11        Keiko Tsushima      Yukiko Shimazaki   353037     Action
12        Shima Iwashita         TetsurÃ´ Tanba    61089     Action
13     Rashmika Mandanna               Sumanth    60082     Action
14       Natalie Portman          Danny Aiello  1190333     Action
15        Connie Nielsen           Oliver Reed  1537293     Action
16      Hailee Steinfeld        Mahershala Ali   574033  Animation
17          Paul Freeman      John Rhys-Davies   987585     Action
18          Mark Ruffalo       Chris Hemsworth  1181806     Action
19          Mark Ruffalo           Chris Evans  1125077     Action
20        Kang Hye-jeong         Kim Byeong-Ok   596920     Action
21         Anne Hathaway           Gary Oldman  1742957     Action
22           Carrie Henn           Paul Reiser   732985     Action
23             Arjun Das         George Maryan    36167     Action
24           Prakash Raj             Pasupathy    31220     Action
25          Miles Teller            Val Kilmer   592075     Action
26            Val Kilmer            Jon Voight   677203     Action
27           James Mason   Jessie Royce Landis   334798     Action
28         Carrie Fisher    Billy Dee Williams  1078425     Action
29           YÃ»ko Tanaka          Billy Crudup   407142  Animation
30         Achyuth Kumar        Sapthami Gowda    95596     Action
31    Fatima Sana Shaikh        Sanya Malhotra   197502     Action
32            Radha Ravi       Sangili Murugan    46988     Action
33        Raveena Tandon       Srinidhi Shetty   139730     Action
34         Fahadh Faasil                Narain    63919     Action
35          Shiv Panditt       Pranay Pachauri   124859     Action
36        Bradley Cooper       Pom Klementieff   159228     Action
37  Benedict Cumberbatch         Jacob Batalon   798974     Action
38         Jeff Goldblum  Richard Attenborough  1014710     Action
39          Alison Doody       Denholm Elliott   771881     Action
40           Daniel Mays           Colin Firth   621897     Action
41          Ken Watanabe           Liam Neeson  1504338     Action
42          Daryl Hannah        Michael Madsen  1141529     Action
43        Bonnie Bedelia   Reginald VelJohnson   901815     Action
44         Rupert Graves           Stephen Rea  1141386     Action
45         Joel Edgerton     Jennifer Morrison   482056     Action
46   Yoshitsugu Matsuoka          Hiro Shimono    64546  Animation
47         Jinpachi Nezu           Daisuke RyÃ»   129268     Action
48      Tigmanshu Dhulia          Richa Chadha    99411     Action
49      Shraddha Srinath                Kathir    47726     Action

        Genre2     Genre3  Gross collection  Popularity Certification
0       Action  Adventure           64518.0           1            PG
1        Crime      Drama         2720822.0           2         PG-13
2    Adventure      Drama               NaN           3         PG-13
3    Adventure     Sci-Fi         1888561.0           4         PG-13
4    Adventure      Drama               NaN           5         PG-13
5    Adventure      Drama         2415126.0           6         PG-13
6       Sci-Fi        NaN               NaN           7             R
7    Adventure    Fantasy         1917162.0           8            PG
8        Drama        NaN               NaN           9         TV-MA
9    Adventure    Fantasy         1704549.0          10            PG
10      Sci-Fi        NaN               NaN          11             R
11       Drama        NaN         1959456.0          12     Not Rated
12       Drama    Mystery               NaN          13     Not Rated
13       Drama    Mystery         1322176.0          14             U
14       Crime      Drama               NaN          15             R
15   Adventure      Drama          119546.0          16             R
16      Action  Adventure         1394619.0          17            PG
17   Adventure        NaN               NaN          18            PG
18   Adventure      Drama         1123902.0          19         PG-13
19   Adventure     Sci-Fi               NaN          20         PG-13
20       Drama    Mystery          353037.0          21             R
21       Drama   Thriller               NaN          22         PG-13
22   Adventure     Sci-Fi           61089.0          23             R
23   Adventure      Crime           60082.0          24     Not Rated
24       Drama        NaN         1190333.0          25     Not Rated
25       Drama        NaN               NaN          26         PG-13
26       Crime      Drama         1537293.0          27             R
27   Adventure    Mystery               NaN          28      Approved
28   Adventure    Fantasy          574033.0          29            PG
29      Action  Adventure               NaN          30         PG-13
30   Adventure      Drama          987585.0          31     Not Rated
31   Biography      Drama               NaN          32     Not Rated
32       Crime      Drama         1181806.0          33     Not Rated
33       Crime      Drama               NaN          34     Not Rated
34       Crime   Thriller         1125077.0          35            UA
35   Biography      Drama               NaN          36         TV-14
36   Adventure     Comedy          596920.0          37         PG-13
37   Adventure    Fantasy               NaN          38         PG-13
38   Adventure     Sci-Fi         1742957.0          39         PG-13
39   Adventure        NaN               NaN          40         PG-13
40       Drama        War          732985.0          41             R
41       Crime      Drama               NaN          42         PG-13
42       Crime      Drama           36167.0          43             R
43    Thriller        NaN           31220.0          44             R
44       Drama     Sci-Fi          592075.0          45             R
45       Drama      Sport               NaN          46         PG-13
46      Action  Adventure          677203.0          47             R
47       Drama        War               NaN          48             R
48      Comedy      Crime          334798.0          49     Not Rated
49       Crime      Drama               NaN          50     Not Rated

# 2)   Display all movie names, Director, ratings, and gross collection where the genre is action.

In [83]:
merged_data = pd.merge(df, df2, on='movie')
action_movies = merged_data[(merged_data['Genre1'] == 'Action') | (merged_data['Genre2'] == 'Action') | (merged_data['Genre3'] == 'Action')]
filtered_data = action_movies[['movie', 'Director1', 'Director2', 'Director3', 'Rating', 'Gross collection', 'Genre1']]
print(filtered_data[['movie', 'Director1', 'Director2', 'Director3', 'Rating', 'Gross collection']])

                                                movie          Director1  \
1                                     The Dark Knight  Christopher Nolan
2       The Lord of the Rings: The Return of the King      Peter Jackson
3                                           Inception  Christopher Nolan
4   The Lord of the Rings: The Fellowship of the Ring      Peter Jackson
5               The Lord of the Rings: The Two Towers      Peter Jackson
6                                          The Matrix     Lana Wachowski
7      Star Wars: Episode V - The Empire Strikes Back     Irvin Kershner
8                                     Soorarai Pottru      Sudha Kongara
9                  Star Wars: Episode IV - A New Hope       George Lucas
10                         Terminator 2: Judgment Day      James Cameron
11                                      Seven Samurai     Akira Kurosawa
12                                           Harakiri   Masaki Kobayashi
13                                         Sita Ramam   Hanu Raghavapudi
14                             LÃ©on: The Professional         Luc Besson
15                                          Gladiator       Ridley Scott
17      Indiana Jones and the Raiders of the Lost Ark   Steven Spielberg
18                                  Avengers: Endgame      Anthony Russo
19                             Avengers: Infinity War      Anthony Russo
20                                             Oldboy     Park Chan-wook
21                              The Dark Knight Rises  Christopher Nolan
22                                             Aliens      James Cameron
23                                             Kaithi   Lokesh Kanagaraj
24                                             Asuran        Vetrimaaran
25                                  Top Gun: Maverick    Joseph Kosinski
26                                               Heat       Michael Mann
27                                 North by Northwest   Alfred Hitchcock
28         Star Wars: Episode VI - Return of the Jedi   Richard Marquand
30                                            Kantara      Rishab Shetty
31                                             Dangal      Nitesh Tiwari
32                                         Raatchasan          Ram Kumar
33                                   K.G.F: Chapter 2     Prashanth Neel
34                                             Vikram   Lokesh Kanagaraj
35                                          Shershaah      Vishnuvardhan
36                     Guardians of the Galaxy Vol. 3         James Gunn
37                            Spider-Man: No Way Home          Jon Watts
38                                      Jurassic Park   Steven Spielberg
39                 Indiana Jones and the Last Crusade   Steven Spielberg
40                                               1917         Sam Mendes
41                                      Batman Begins  Christopher Nolan
42                                  Kill Bill: Vol. 1  Quentin Tarantino
43                                           Die Hard     John McTiernan
44                                     V for Vendetta     James McTeigue
45                                            Warrior     Gavin O'Connor
47                                                Ran     Akira Kurosawa
48                                 Gangs of Wasseypur     Anurag Kashyap
49                                       Vikram Vedha            Gayatri

          Director2         Director3  Rating  Gross collection
1                                         9.0         2720822.0
2                                         9.0               NaN
3                                         8.8         1888561.0
4                                         8.8               NaN
5                                         8.8         2415126.0
6   Lilly Wachowski                       8.7               NaN
7                                         8.7         1917162.0
8                                         8.7               NaN
9                                         8.6         1704549.0
10                                        8.6               NaN
11                                        8.6         1959456.0
12                                        8.6               NaN
13                                        8.6         1322176.0
14                                        8.5               NaN
15                                        8.5          119546.0
17                                        8.4               NaN
18        Joe Russo                       8.4         1123902.0
19        Joe Russo                       8.4               NaN
20                                        8.4          353037.0
21                                        8.4               NaN
22                                        8.4           61089.0
23                                        8.4           60082.0
24                                        8.4         1190333.0
25                                        8.3               NaN
26                                        8.3         1537293.0
27                                        8.3               NaN
28                                        8.3          574033.0
30                                        8.3          987585.0
31                                        8.3               NaN
32                                        8.3         1181806.0
33                                        8.3               NaN
34                                        8.3         1125077.0
35                                        8.3               NaN
36                                        8.2          596920.0
37                                        8.2               NaN
38                                        8.2         1742957.0
39                                        8.2               NaN
40                                        8.2          732985.0
41                                        8.2               NaN
42                                        8.2           36167.0
43                                        8.2           31220.0
44                                        8.2          592075.0
45                                        8.2               NaN
47                                        8.2               NaN
48                                        8.2          334798.0
49          Pushkar  Gowtham Selvaraj     8.2               NaN

# 3)      Display all details from both tables with the highest gross collection

In [92]:

# Find the movie with the highest gross collection in df2
max_gross_df2 = df2[df2['Gross collection'] == df2['Gross collection'].max()]

# Get the movie names with the highest gross collection
highest_gross_movie = max_gross_df2['movie'].values[0]

# Find all movies with the same name in df and df2
matched_movies_df = pd.concat([df[df['movie'] == highest_gross_movie], df2[df2['movie'] == highest_gross_movie]])

# Display all details of the matched movies with the highest gross collection
print(matched_movies_df)

             movie          Director1 Director2 Director3  Duration  \
1  The Dark Knight  Christopher Nolan                         152.0
1  The Dark Knight                NaN       NaN       NaN       NaN

   year of release  Rating Meatscore          Star_1        Star_2  \
1           2008.0     9.0        84             NaN           NaN
1              NaN     NaN       NaN  Christian Bale  Heath Ledger

          Star_3         Star_4      Votes  Genre1  Genre2 Genre3  \
1            NaN            NaN        NaN     NaN     NaN    NaN
1  Aaron Eckhart  Michael Caine  2720822.0  Action   Crime  Drama

   Gross collection  Popularity Certification
1               NaN         NaN           NaN
1         2720822.0         2.0         PG-13

# 4)      Display all details from both tables with the highest ratings

In [97]:
# Find the movie with the highest rating in df
max_rating_df = df[df['Rating'] == df['Rating'].max()]

# Get the movie name with the highest rating
highest_rating_movie = max_rating_df['movie'].values[0]

# Find all movies with the same name in df2
matched_movies_df2 = df2[df2['movie'] == highest_rating_movie]

# Display all details of the matched movies with the highest rating
matched_movies_df = pd.concat([max_rating_df, matched_movies_df2])
print("Top Movie",matched_movies_df)

Top Movie                                  movie           Director1    Director2  \
0  Spider-Man: Across the Spider-Verse  Joaquim Dos Santos  Kemp Powers
0  Spider-Man: Across the Spider-Verse                 NaN          NaN

            Director3  Duration  year of release  Rating Meatscore  \
0  Justin K. Thompson     140.0           2023.0     9.1        87
0                 NaN       NaN              NaN     NaN       NaN

          Star_1            Star_2             Star_3             Star_4  \
0            NaN               NaN                NaN                NaN
0  Shameik Moore  Hailee Steinfeld  Brian Tyree Henry  Luna Lauren Velez

     Votes     Genre1   Genre2     Genre3  Gross collection  Popularity  \
0      NaN        NaN      NaN        NaN               NaN         NaN
0  64518.0  Animation   Action  Adventure           64518.0         1.0

  Certification
0           NaN
0            PG

# 5 )      Display all details from both tables with the lowest gross collection and lowest ratings

In [99]:

# Find the movie with the lowest gross collection in df2
min_gross_df2 = df2[df2['Gross collection'] == df2['Gross collection'].min()]

# Get the movie name with the lowest gross collection
lowest_gross_movie = min_gross_df2['movie'].values[0]

# Find all movies with the same name in df
matched_movies_df = df[df['movie'] == lowest_gross_movie]

# Display all details of the matched movies with the lowest gross collection
combined_data = pd.concat([matched_movies_df, min_gross_df2])
print(combined_data)
print ('The lowest Gross collection')

       movie       Director1 Director2 Director3  Duration  year of release  \
43  Die Hard  John McTiernan                         132.0           1988.0
43  Die Hard             NaN       NaN       NaN       NaN              NaN

    Rating Meatscore        Star_1        Star_2          Star_3  \
43     8.2        72           NaN           NaN             NaN
43     NaN       NaN  Bruce Willis  Alan Rickman  Bonnie Bedelia

                 Star_4     Votes  Genre1     Genre2 Genre3  Gross collection  \
43                  NaN       NaN     NaN        NaN    NaN               NaN
43  Reginald VelJohnson  901815.0  Action   Thriller    NaN           31220.0

    Popularity Certification
43         NaN           NaN
43        44.0             R
The lowest Gross collection

# Now once completed with queries in the SQLite database, then make the exact query solutions by using PANDAS SQL in the data frame.  Load the CSV data in a data frame and start making solutions for all the above 15 queries using PANDAS SQL. You may use concat or merge joins per the requirements basis to make 5 join queries.

# 1)  Display all the details of movies created by directors Christopher and Matt Reeves.

In [105]:
import pandas as pd
from pandasql import sqldf

# Load the CSV data into DataFrames
df = pd.read_csv('directors_data.csv')

# Define the SQL query
query = "SELECT * FROM df WHERE Director1 IN ('Christopher Nolan', 'Matt Reeves') OR Director2 IN ('Christopher Nolan', 'Matt Reeves') OR Director3 IN ('Christopher Nolan', 'Matt Reeves')"

# Execute the SQL query using pandasql
result = sqldf(query)

# Display the result
print(result)

                   movie          Director1 Director2 Director3  Duration  \
0        The Dark Knight  Christopher Nolan                           152
1              Inception  Christopher Nolan                           148
2  The Dark Knight Rises  Christopher Nolan                           164
3          Batman Begins  Christopher Nolan                           140

   year of release  Rating Meatscore
0             2008     9.0        84
1             2010     8.8        74
2             2012     8.4        78
3             2005     8.2        70

# 2) Display all the details of movies with a duration of 140 minutes to 190 minutes.

In [107]:

# Load the CSV data into a DataFrame
df = pd.read_csv('directors_data.csv')

# Define the SQL query
query = "SELECT * FROM df WHERE Duration BETWEEN 140 AND 190"

# Execute the SQL query using pandasql
result = sqldf(query)

# Print the result
print(result)

                                                movie           Director1  \
0                 Spider-Man: Across the Spider-Verse  Joaquim Dos Santos
1                                     The Dark Knight   Christopher Nolan
2                                           Inception   Christopher Nolan
3   The Lord of the Rings: The Fellowship of the Ring       Peter Jackson
4               The Lord of the Rings: The Two Towers       Peter Jackson
5                                     Soorarai Pottru       Sudha Kongara
6                                          Sita Ramam    Hanu Raghavapudi
7                                           Gladiator        Ridley Scott
8                                   Avengers: Endgame       Anthony Russo
9                              Avengers: Infinity War       Anthony Russo
10                              The Dark Knight Rises   Christopher Nolan
11                                             Kaithi    Lokesh Kanagaraj
12                                             Asuran         Vetrimaaran
13                                               Heat        Michael Mann
14                                            Kantara       Rishab Shetty
15                                             Dangal       Nitesh Tiwari
16                                         Raatchasan           Ram Kumar
17                                   K.G.F: Chapter 2      Prashanth Neel
18                                             Vikram    Lokesh Kanagaraj
19                     Guardians of the Galaxy Vol. 3          James Gunn
20                            Spider-Man: No Way Home           Jon Watts
21                                      Batman Begins   Christopher Nolan
22                                            Warrior      Gavin O'Connor
23                                                Ran      Akira Kurosawa
24                                       Vikram Vedha             Gayatri

      Director2           Director3  Duration  year of release  Rating  \
0   Kemp Powers  Justin K. Thompson       140             2023     9.1
1                                         152             2008     9.0
2                                         148             2010     8.8
3                                         178             2001     8.8
4                                         179             2002     8.8
5                                         153             2020     8.7
6                                         163             2022     8.6
7                                         155             2000     8.5
8     Joe Russo                           181             2019     8.4
9     Joe Russo                           149             2018     8.4
10                                        164             2012     8.4
11                                        145             2019     8.4
12                                        141             2019     8.4
13                                        170             1995     8.3
14                                        148             2022     8.3
15                                        161             2016     8.3
16                                        170             2018     8.3
17                                        168             2022     8.3
18                                        175             2022     8.3
19                                        150             2023     8.2
20                                        148             2021     8.2
21                                        140             2005     8.2
22                                        140             2011     8.2
23                                        162             1985     8.2
24      Pushkar    Gowtham Selvaraj       147             2017     8.2

   Meatscore
0         87
1         84
2         74
3         92
4         87
5
6
7         67
8         78
9         68
10        78
11
12
13        76
14
15
16
17
18
19        64
20        71
21        70
22        71
23        97
24

# 3) Display all details of movies with ratings above 7 in ascending order.

In [108]:
# Load the CSV data into a DataFrame
df = pd.read_csv('directors_data.csv')

# Define the SQL query
query = "SELECT * FROM df WHERE Rating > 7 ORDER BY Rating ASC"

# Execute the SQL query using pandasql
result = sqldf(query)

# Print the result
print(result)

                                                movie           Director1  \
0                      Guardians of the Galaxy Vol. 3          James Gunn
1                             Spider-Man: No Way Home           Jon Watts
2                                       Jurassic Park    Steven Spielberg
3                  Indiana Jones and the Last Crusade    Steven Spielberg
4                                                1917          Sam Mendes
5                                       Batman Begins   Christopher Nolan
6                                   Kill Bill: Vol. 1   Quentin Tarantino
7                                            Die Hard      John McTiernan
8                                      V for Vendetta      James McTeigue
9                                             Warrior      Gavin O'Connor
10                Demon Slayer the Movie: Mugen Train      Haruo Sotozaki
11                                                Ran      Akira Kurosawa
12                                 Gangs of Wasseypur      Anurag Kashyap
13                                       Vikram Vedha             Gayatri
14                                  Top Gun: Maverick     Joseph Kosinski
15                                               Heat        Michael Mann
16                                 North by Northwest    Alfred Hitchcock
17         Star Wars: Episode VI - Return of the Jedi    Richard Marquand
18                                  Princess Mononoke      Hayao Miyazaki
19                                            Kantara       Rishab Shetty
20                                             Dangal       Nitesh Tiwari
21                                         Raatchasan           Ram Kumar
22                                   K.G.F: Chapter 2      Prashanth Neel
23                                             Vikram    Lokesh Kanagaraj
24                                          Shershaah       Vishnuvardhan
25                  Spider-Man: Into the Spider-Verse     Bob Persichetti
26      Indiana Jones and the Raiders of the Lost Ark    Steven Spielberg
27                                  Avengers: Endgame       Anthony Russo
28                             Avengers: Infinity War       Anthony Russo
29                                             Oldboy      Park Chan-wook
30                              The Dark Knight Rises   Christopher Nolan
31                                             Aliens       James Cameron
32                                             Kaithi    Lokesh Kanagaraj
33                                             Asuran         Vetrimaaran
34                             LÃ©on: The Professional          Luc Besson
35                                          Gladiator        Ridley Scott
36                 Star Wars: Episode IV - A New Hope        George Lucas
37                         Terminator 2: Judgment Day       James Cameron
38                                      Seven Samurai      Akira Kurosawa
39                                           Harakiri    Masaki Kobayashi
40                                         Sita Ramam    Hanu Raghavapudi
41                                         The Matrix      Lana Wachowski
42     Star Wars: Episode V - The Empire Strikes Back      Irvin Kershner
43                                    Soorarai Pottru       Sudha Kongara
44                                          Inception   Christopher Nolan
45  The Lord of the Rings: The Fellowship of the Ring       Peter Jackson
46              The Lord of the Rings: The Two Towers       Peter Jackson
47                                    The Dark Knight   Christopher Nolan
48      The Lord of the Rings: The Return of the King       Peter Jackson
49                Spider-Man: Across the Spider-Verse  Joaquim Dos Santos

          Director2           Director3  Duration  year of release  Rating  \
0                                             150             2023     8.2
1                                             148             2021     8.2
2                                             127             1993     8.2
3                                             127             1989     8.2
4                                             119             2019     8.2
5                                             140             2005     8.2
6                                             111             2003     8.2
7                                             132             1988     8.2
8                                             132             2005     8.2
9                                             140             2011     8.2
10                                            117             2020     8.2
11                                            162             1985     8.2
12                                            321             2012     8.2
13          Pushkar    Gowtham Selvaraj       147             2017     8.2
14                                            130             2022     8.3
15                                            170             1995     8.3
16                                            136             1959     8.3
17                                            131             1983     8.3
18                                            134             1997     8.3
19                                            148             2022     8.3
20                                            161             2016     8.3
21                                            170             2018     8.3
22                                            168             2022     8.3
23                                            175             2022     8.3
24                                            135             2021     8.3
25     Peter Ramsey      Rodney Rothman       117             2018     8.4
26                                            115             1981     8.4
27        Joe Russo                           181             2019     8.4
28        Joe Russo                           149             2018     8.4
29                                            101             2003     8.4
30                                            164             2012     8.4
31                                            137             1986     8.4
32                                            145             2019     8.4
33                                            141             2019     8.4
34                                            110             1994     8.5
35                                            155             2000     8.5
36                                            121             1977     8.6
37                                            137             1991     8.6
38                                            207             1954     8.6
39                                            133             1962     8.6
40                                            163             2022     8.6
41  Lilly Wachowski                           136             1999     8.7
42                                            124             1980     8.7
43                                            153             2020     8.7
44                                            148             2010     8.8
45                                            178             2001     8.8
46                                            179             2002     8.8
47                                            152             2008     9.0
48                                            201             2003     9.0
49      Kemp Powers  Justin K. Thompson       140             2023     9.1

   Meatscore
0         64
1         71
2         68
3         65
4         78
5         70
6         69
7         72
8         62
9         71
10        72
11        97
12        89
13
14        78
15        76
16        98
17        58
18        76
19
20
21
22
23
24
25        87
26        85
27        78
28        68
29        77
30        78
31        84
32
33
34        64
35        67
36        90
37        75
38        98
39        85
40
41        73
42        82
43
44        74
45        92
46        87
47        84
48        94
49        87

# 4) Display all movie names in descending orde

In [109]:
# Load the CSV data into a DataFrame
df = pd.read_csv('directors_data.csv')

# Define the SQL query
query = "SELECT movie FROM df ORDER BY movie DESC"

# Execute the SQL query using pandasql
result = sqldf(query)

# Print the result
print(result)

                                                movie
0                                             Warrior
1                                        Vikram Vedha
2                                              Vikram
3                                      V for Vendetta
4                                   Top Gun: Maverick
5                                          The Matrix
6               The Lord of the Rings: The Two Towers
7       The Lord of the Rings: The Return of the King
8   The Lord of the Rings: The Fellowship of the Ring
9                               The Dark Knight Rises
10                                    The Dark Knight
11                         Terminator 2: Judgment Day
12         Star Wars: Episode VI - Return of the Jedi
13     Star Wars: Episode V - The Empire Strikes Back
14                 Star Wars: Episode IV - A New Hope
15                            Spider-Man: No Way Home
16                  Spider-Man: Into the Spider-Verse
17                Spider-Man: Across the Spider-Verse
18                                    Soorarai Pottru
19                                         Sita Ramam
20                                          Shershaah
21                                      Seven Samurai
22                                                Ran
23                                         Raatchasan
24                                  Princess Mononoke
25                                             Oldboy
26                                 North by Northwest
27                             LÃ©on: The Professional
28                                  Kill Bill: Vol. 1
29                                            Kantara
30                                             Kaithi
31                                   K.G.F: Chapter 2
32                                      Jurassic Park
33      Indiana Jones and the Raiders of the Lost Ark
34                 Indiana Jones and the Last Crusade
35                                          Inception
36                                               Heat
37                                           Harakiri
38                     Guardians of the Galaxy Vol. 3
39                                          Gladiator
40                                 Gangs of Wasseypur
41                                           Die Hard
42                Demon Slayer the Movie: Mugen Train
43                                             Dangal
44                                      Batman Begins
45                             Avengers: Infinity War
46                                  Avengers: Endgame
47                                             Asuran
48                                             Aliens
49                                               1917

# 5) Display movie name starts with âPâ and their rating is greater than 7.

In [110]:
# Load the CSV data into a DataFrame
df = pd.read_csv('directors_data.csv')

# Define the SQL query
query = "SELECT movie FROM df WHERE movie LIKE 'P%' AND Rating > 7"

# Execute the SQL query using pandasql
result = sqldf(query)

# Print the result
print(result)

               movie
0  Princess Mononoke

# Table 2: Movie Name, stars, votes, Genre, Gross collection, popularity, Certification

# 1) Display all movie names with star Arnold Schwarzenegger in ascending order.

In [112]:
# Load the CSV data into a DataFrame
df = pd.read_csv('movies_data.csv')

# Define the SQL query
query = "SELECT movie FROM df WHERE Star_1 = 'Arnold Schwarzenegger' ORDER BY movie ASC"

# Execute the SQL query using pandasql
result = sqldf(query)

# Print the result
print(result)

                        movie
0  Terminator 2: Judgment Day

# 2) Display all details of the movie with the highest number of votes.

In [113]:
# Load the CSV data into a DataFrame
df = pd.read_csv('movies_data.csv')

# Define the SQL query
query = "SELECT * FROM df ORDER BY Votes DESC LIMIT 1"

# Execute the SQL query using pandasql
result = sqldf(query)

# Print the result
print(result)

             movie          Star_1        Star_2         Star_3  \
0  The Dark Knight  Christian Bale  Heath Ledger  Aaron Eckhart

          Star_4    Votes  Genre1  Genre2 Genre3  Gross collection  \
0  Michael Caine  2720822  Action   Crime  Drama         2720822.0

   Popularity Certification
0           2         PG-13

# 3) Display movie names with gross collections in descending order

In [114]:
# Load the CSV data into a DataFrame
df = pd.read_csv('movies_data.csv')

# Define the SQL query
query = "SELECT movie, `Gross collection` FROM df ORDER BY `Gross collection` DESC"

# Execute the SQL query using pandasql
result = sqldf(query)

# Print the result
print(result)

                                                movie  Gross collection
0                                     The Dark Knight         2720822.0
1               The Lord of the Rings: The Two Towers         2415126.0
2                                       Seven Samurai         1959456.0
3      Star Wars: Episode V - The Empire Strikes Back         1917162.0
4                                           Inception         1888561.0
5                                       Jurassic Park         1742957.0
6                  Star Wars: Episode IV - A New Hope         1704549.0
7                                                Heat         1537293.0
8                   Spider-Man: Into the Spider-Verse         1394619.0
9                                          Sita Ramam         1322176.0
10                                             Asuran         1190333.0
11                                         Raatchasan         1181806.0
12                                             Vikram         1125077.0
13                                  Avengers: Endgame         1123902.0
14                                            Kantara          987585.0
15                                               1917          732985.0
16                Demon Slayer the Movie: Mugen Train          677203.0
17                     Guardians of the Galaxy Vol. 3          596920.0
18                                     V for Vendetta          592075.0
19         Star Wars: Episode VI - Return of the Jedi          574033.0
20                                             Oldboy          353037.0
21                                 Gangs of Wasseypur          334798.0
22                                          Gladiator          119546.0
23                Spider-Man: Across the Spider-Verse           64518.0
24                                             Aliens           61089.0
25                                             Kaithi           60082.0
26                                  Kill Bill: Vol. 1           36167.0
27                                           Die Hard           31220.0
28      The Lord of the Rings: The Return of the King               NaN
29  The Lord of the Rings: The Fellowship of the Ring               NaN
30                                         The Matrix               NaN
31                                    Soorarai Pottru               NaN
32                         Terminator 2: Judgment Day               NaN
33                                           Harakiri               NaN
34                             LÃ©on: The Professional               NaN
35      Indiana Jones and the Raiders of the Lost Ark               NaN
36                             Avengers: Infinity War               NaN
37                              The Dark Knight Rises               NaN
38                                  Top Gun: Maverick               NaN
39                                 North by Northwest               NaN
40                                  Princess Mononoke               NaN
41                                             Dangal               NaN
42                                   K.G.F: Chapter 2               NaN
43                                          Shershaah               NaN
44                            Spider-Man: No Way Home               NaN
45                 Indiana Jones and the Last Crusade               NaN
46                                      Batman Begins               NaN
47                                            Warrior               NaN
48                                                Ran               NaN
49                                       Vikram Vedha               NaN

# 5) Display the gross collection of movies with the star Arnold.

In [116]:

# Load the CSV data into a DataFrame
df = pd.read_csv('movies_data.csv')

# Define the SQL query
query = "SELECT movie, `Gross collection` FROM df WHERE Star_1 LIKE '%Arnold%' OR Star_2 LIKE '%Arnold%' OR Star_3 LIKE '%Arnold%' OR Star_4 LIKE '%Arnold%'"

# Execute the SQL query using pandasql
result = sqldf(query)

# Print the result
print(result)

                        movie Gross collection
0  Terminator 2: Judgment Day             None